modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"

[[mods]]
modId = "immersiveoverlays"
version = "${version}"
displayName = "Immersive Overlays"
authors = "cassiancc, noelledotjpg"
description = '''
Overlays useful info like coordinates and the time - as long as you have the right item.
'''
logoFile = "icon.png"
issueTrackerURL = "https://github.com/cassiancc/Immersive-Overlays/issues"
displayURL="https://modrinth.com/mod/immersive-overlays"
modURL="https://modrinth.com/mod/immersive-overlays"
credits = "Additional sprites from ProbablyEkho, Crabbarition, Kelpiesaurus, and KevBo"

[[dependencies.immersiveoverlays]]
modId = "forge"
mandatory = true
versionRange = "[43,50)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.immersiveoverlays]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.2)"
ordering = "NONE"
side = "CLIENT"